auth_url='http://uninstall.io/api/v1/auth/token'
application_url='http://uninstall.io/api/v1/applications'
count_url = 'http://uninstall.io/api/v1/charts/counts?app='
chart_uninstalls_url='http://uninstall.io/api/v1/charts/uninstalls?app='
chart_reinstalls_url='http://uninstall.io/api/v1/charts/reinstalls?app='
chart_events_url='http://uninstall.io/api/v1/charts/events?app='
chart_source_url='http://uninstall.io/api/v1/values/sources?app='
chart_device_url='http://uninstall.io/api/v1/values/devices?app='
chart_insights_url='http://uninstall.io/api/v1/charts/insights?app='
chart_retention_url='http://uninstall.io/api/v1/charts/retention?app'
chart_cohort_url='http://uninstall.io/api/v1/charts/cohort?app='
chart_installs_by_day_url='http://uninstall.io/api/v1/charts/installs_by_day?app='
chart_action_installs='http://uninstall.io/api/v1/charts/action_results?app='


